# Portapps
core.dir = ../portapps

# App
app = opera
app.name = Opera
app.type = archive
app.version = 133.0.5932
app.release = 23
app.homepage = https://www.opera.com
# Chromium version 121.0.6167.140, useful info for bithack

# Portable app
papp.id = ${app}-portable
papp.guid = {8AEE810B-2E26-4D32-B54F-64313E55C4AC}
papp.name = ${app.name} Portable
papp.desc = ${app.name} portable on Windows by Portapps
papp.url = https://github.com/portapps/${papp.id}
papp.folder = app

# Official artifacts
atf.id = Opera
atf.win64.filename = opera_x64
atf.win64.ext = .exe
#atf.win64.url = https://download3.operacdn.com/ftp/pub/opera/desktop/${app.version}.${app.release}/win/Opera_${app.version}.${app.release}_Setup_x64.exe
#atf.win64.url = https://download3.operacdn.com/ftp/pub/opera_gx/${app.version}.${app.release}/win/Opera_GX_${app.version}.${app.release}_Setup_x64.exe
atf.win64.url = https://download3.operacdn.com/ftp/pub/opera_air/${app.version}.${app.release}/win/Opera_Air_${app.version}.${app.release}_Setup_x64.exe
# atf.win32.url = https://download3.operacdn.com/ftp/pub/opera/desktop/107.0.5045.36/win/Opera_107.0.5045.36_Setup.exe
atf.win64.assertextract = opera.exe
